title = "My Climate Blog"
baseURL = "https://dhamsey3.github.io/trish/"
languageCode = "en-us"

[params]
heroTitle = "Climate & Everyday Choices"
heroText  = "Stories, definitions, and experiments in sustainability — auto-synced from Medium."

[params.social]
medium   = "https://medium.com/@myclimatedefinition"
linkedin = "https://www.linkedin.com/in/yourprofile/"
twitter  = "https://twitter.com/yourhandle"
email    = "you@example.com"

[menu]
  [[menu.main]]
  name = "Home"
  url  = "/"
  weight = 1
