name: Build & Deploy Hugo (Medium feed)

on:
  push:
    branches: ["main", "master"]
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install feedparser
        run: pip install feedparser

      - name: Generate Markdown posts from Medium feed
        run: |
          python - << 'PY'
import feedparser, os, re, pathlib, textwrap, html
FEED_URL = "https://medium.com/feed/@myclimatedefinition" 
feed = feedparser.parse(FEED_URL)
outdir = pathlib.Path("content/medium")
outdir.mkdir(parents=True, exist_ok=True)

def slugify(t):
    return re.sub(r'[^a-z0-9-]+','-', t.lower()).strip('-')

for e in feed.entries:
    title = e.get("title","Untitled")
    link  = e.get("link","#")
    date  = e.get("published","")
    summ  = e.get("summary","")
    body  = textwrap.shorten(html.unescape(re.sub("<.*?>","",summ)), 280)
    slug  = slugify(title) or slugify(link)
    md = f"""+++
title = "{title.replace('"','\\"')}"
date = "{date}"
draft = false
external_url = "{link}"
+++

{body}

[Read on Medium →]({link})
"""
    (outdir / f"{slug}.md").write_text(md, encoding="utf-8")

print(f"Wrote {len(feed.entries)} markdown posts to content/medium/")
PY

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.126.1"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
